name: epr
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - blas
  - ca-certificates
  - certifi
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - ipython
  - ipython_genutils
  - jedi
  - jpeg
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prompt-toolkit
  - ptyprocess
  - pyface
  - pygments
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - readline
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - traitlets
  - traits
  - traitsui
  - wcwidth
  - wheel
  - xz
  - zlib

